---
# tasks file for first_role
- name: change default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: add index.html
  file:
    path: /var/www/html/index.html
    state: touch
  
- name: add line in file
  lineinfile:
    path: /var/www/html/index.html
    line: "<h1> Welcome to Skillstorm </h1>"